### ISSUE TITLE
Refactor project README.md structure

### ISSUE THREAD

**Issue by vchendrix** [BASIN-3D/basin3d#36]
Refactor REAMDE.md structure to be more user friendly.

+ New README.md structure 
    + project name  (README.md)
    + description  (README.md)
    + link to documentation website  (README.md)
    + installation instructions  (README.md)
    + Link to how to contribute (CONTRIBUTE.md)
    + Change log (CHANGES.md) - with the 2 versions and releases
    + Authors 
    + License (LICENSE.md)
    + Copyright (README.md)
    + Acknowledgements (README.md) - make comment and ask charu
+ ~Update license file (to with repostory name)~
+ Add  a contributing file with getting started for developers. (add dev practices, documentation, testing, etc.)
+ Update `setup.py` with updated information 
+ ~Setup github io docs~ (moved to separate ticket)

```
setup(name='basin3d',
      version=__release__,
      description='BASIN-3D Core Framework',
      long_description=README,
      author='Val Hendrix, <list all authors>',
      author_email='vchendrix@lbl.gov, <list all author emails>',
      url='https://github.com/BASIN-3D/basin3d',
      packages=packages,
      data_files=['basin3d/data/basin3d_variables_hydrology.csv',
                  'basin3d/plugins/mapping_usgs.csv'],
      include_package_data=True,
      install_requires=[
         "pandas",
         "pyyaml",
         "requests",
         "tinydb"
      ]
      )
```

**Comment by heycatwonton** [comment]
In order to get Github Pages to work:

1. Create an empty `.nojekyll` file in the `docs` directory (root) to turn off Jekyll.
2. Create `index.html` file in the `docs` directory (root) with contents:

-  `<meta http-equiv="refresh" content="0; url=./docsrc/html/index.html" />`

3. Create seperate directory `docsrc`, to build documentation and add `docsrc` directory to repo
4. Change the Sphinx build directory to docs in your Makefile for example as follows:
`BUILDDIR = docsrc`
5. Run make html 
6. add, commit and push: 
       
-  docsrc/
-  index.html
-  .nojekyll
-  Makefile 

7. In Settings -> GitHub Pages -> Source -> choose `<branch>/docs`
8. Visit https://heycatwonton.github.io/basin3d/

**Comment by heycatwonton** [comment]
TODO: pip install directory from repo

**Comment by charuleka** [comment]
Please use the following instead:
This research is supported as part of the Watershed Function Scientific
Focus Area and a DOE Early Career Project funded by the U.S. Department of
Energy, Office of Science, Office of Biological and Environmental Research
under Award no. DE-AC02-05CH11231. This research used resources of the
National Energy Research Scientific Computing Center (NERSC), a U.S.
Department of Energy Office of Science User Facility operated under
Contract No. DE-AC02-05CH11231.

**Comment by heycatwonton** [comment]
closing issue manually because Github did not close it automatically
